# Nombre de la aplicacion
spring.application.name=Vantryx AI

# Configuracion de Conexion (Coincide con lo que pusimos en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/vantryx_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia de creacion de tablas (Hibernate)
# 'update' creara las tablas automaticamente basandose en nuestras clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT Configuration
# Esta clave debe ser larga (minimo 256 bits) y compleja.
# En produccion, esto iria en una variable de entorno, nunca aqui.
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
# 86400000 ms = 24 horas de validez
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.writer-with-default-pretty-printer=true

# Configuracion de Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.timeout=300000
spring.mvc.async.request-timeout=300000

# Configuraci\u00F3n b\u00E1sica (Ejemplo para Mailtrap o Gmail)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=f032a3df3c8469
spring.mail.password=365df732d09ddb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

